### ISSUE TITLE
installation on MacOS

### ISSUE THREAD

**Issue by ET18** [Blawx/blawx#53]
Is it possible to install Blawx on MacOS?  http://app.blawx.com/blawx.html site cannot be reached for live app.

**Comment by Gauntlet173** [comment]
Thanks for the heads up on the live app. I'll look into that shortly. Because it is a docker container it SHOULD be possible to run on MacOS if you have docker installed. But I can't say that I've tried it, or heard from anyone who has. If you give it a shot, let me know. I'll update you here when the site is back up.

**Comment by Gauntlet173** [comment]
app.blawx.com is now back up and running, but there are problems with the SSL certificates, so the https version will give you a warning for the time being. I'll try to fix that ASAP. Thanks again for the heads up.

**Comment by Gauntlet173** [comment]
Docket desktop is not currently compatible with the Apple M1 chip, so it is complicated to install on ARM. But if you are using a Mac that can run docker desktop, you should be fine. Let me know if you run into specific problems.
